apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-ops-view
spec:
  rules:
  - host: "kube-ops-view.example.org"
    http:
      paths:
      - backend:
          serviceName: kube-ops-view
          servicePort: 80
