apiVersion: v1
kind: Service
metadata:
  labels:
    application: kube-ops-view-redis
  name: kube-ops-view-redis
spec:
  selector:
    application: kube-ops-view-redis
  type: ClusterIP
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
